__title__ = 'Transclip'
__description__ = 'A small utility to translate clipboard content'
__url__ = 'https://github.com/jhondev-code/Transclip'
__version__ = '2.0.0'
__author__ = 'Jhon fernandez'
__author_email__ = 'jhondev.code@gmail.com'
__license__ = 'GPL-3.0'
__copyright__ = 'Copyright 2021 jhondev-code'
